//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agencia
    {
        public string Cod_Agencia { get; set; }
        public string Nombre_Agencia { get; set; }
        public string Imagen { get; set; }
        public string Cod_Pais_FK { get; set; }
    
        public virtual Pais Pais { get; set; }
    }
}
