//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public string Cod_Registro { get; set; }
        public string Cod_User_FK { get; set; }
        public string FechaTime { get; set; }
        public string Tipo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
