//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public string Codigo_Compras { get; set; }
        public string Cod_User_FK { get; set; }
        public string Codigo_Vuelo_FK { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Vuelos Vuelos { get; set; }
    }
}
