//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consecutivos
    {
        public string Codigo_Consecutivo { get; set; }
        public string Descripcion { get; set; }
        public string Valor { get; set; }
        public string Prefijo { get; set; }
        public string Rango_Ini { get; set; }
        public string Rango_Fin { get; set; }
    }
}
