//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        public Pais()
        {
            this.Agencia = new HashSet<Agencia>();
            this.Vuelos = new HashSet<Vuelos>();
        }
    
        public string Cod_Pais { get; set; }
        public string Nombre_Pais { get; set; }
        public string Imagen { get; set; }
    
        public virtual ICollection<Agencia> Agencia { get; set; }
        public virtual ICollection<Vuelos> Vuelos { get; set; }
    }
}
