//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puerta
    {
        public Puerta()
        {
            this.Vuelos = new HashSet<Vuelos>();
        }
    
        public string Cod_Puerta { get; set; }
        public string Numero_Puerta { get; set; }
        public string Detalle { get; set; }
    
        public virtual ICollection<Vuelos> Vuelos { get; set; }
    }
}
