//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Bitacora = new HashSet<Bitacora>();
            this.Reservas = new HashSet<Reservas>();
            this.Compras = new HashSet<Compras>();
        }
    
        public string Cod_User { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Rol { get; set; }
    
        public virtual ICollection<Bitacora> Bitacora { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
        public virtual ICollection<Compras> Compras { get; set; }
    }
}
