//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoV.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VueloEntities : DbContext
    {
        public VueloEntities()
            : base("name=VueloEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Agencia> Agencia { get; set; }
        public DbSet<Bitacora> Bitacora { get; set; }
        public DbSet<Pais> Pais { get; set; }
        public DbSet<Puerta> Puerta { get; set; }
        public DbSet<Reservas> Reservas { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Vuelos> Vuelos { get; set; }
        public DbSet<Compras> Compras { get; set; }
        public DbSet<Consecutivos> Consecutivos { get; set; }
        public DbSet<Errors> Errors { get; set; }
    }
}
