//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelos
    {
        public Vuelos()
        {
            this.Reservas = new HashSet<Reservas>();
            this.Compras = new HashSet<Compras>();
        }
    
        public string Codigo_Vuelo { get; set; }
        public string Aerolinea { get; set; }
        public string Cod_Pais_FK { get; set; }
        public string Fecha { get; set; }
        public string Hora { get; set; }
        public string Estado { get; set; }
        public string Cod_Puerta_FK { get; set; }
        public string CS { get; set; }
    
        public virtual Pais Pais { get; set; }
        public virtual Puerta Puerta { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
        public virtual ICollection<Compras> Compras { get; set; }
    }
}
